version: 0.2

phases:
  build:
    commands:
      - ls -lah  # List files to check if lambda_function.zip is present
  post_build:
    commands:
      - echo "Uploading ZIP to S3..."
      - aws s3 cp lambda_function.zip s3://passwordreset-bucket/
      - echo "ZIP uploaded to S3"
artifacts:
  files:
    - lambda_function.zip
